FROM node:24-alpine

WORKDIR /app

RUN apk add --no-cache netcat-openbsd

COPY package*.json ./
COPY tsconfig.json ./
COPY tsconfig.test.json ./
COPY jest.config.js ./

RUN npm ci

COPY src ./src
COPY tests ./tests
COPY test-entrypoint.sh ./

RUN chmod +x test-entrypoint.sh

ENTRYPOINT ["./test-entrypoint.sh"]

